import type { RoleProperty } from "@/typings/constants";
import { DoorTiles, RoleTiles } from "../id";

export const HeroNumerical = {
  Name: "英雄",
  HP: 1000,
  ATK: 10,
  DEF: 10,
  XP: 0,
  Gold: 0,
  MP: 0,
  _key: {
    [DoorTiles.RED]: 1,
    [DoorTiles.BLUE]: 1,
    [DoorTiles.YELLOW]: 1,
  },
};

export const RoleNumerical: {
  [key in Exclude<RoleTiles, RoleTiles.HERO>]: RoleProperty;
} = {
  [RoleTiles.SLIME_GREEN]: {
    Name: "绿色史莱姆",
    HP: 50,
    ATK: 20,
    DEF: 1,
    Gold: 1,
    XP: 1,
    MP: 0,
  },

  [RoleTiles.SLIME_RED]: {
    Name: "红色史莱姆",
    HP: 70,
    ATK: 15,
    DEF: 2,
    Gold: 2,
    XP: 2,
    MP: 0,
  },
  [RoleTiles.SLIME_BLACK]: {
    Name: "黑色史莱姆",
    HP: 200,
    ATK: 35,
    DEF: 10,
    Gold: 5,
    XP: 5,
    MP: 0,
  },
  [RoleTiles.ORC]: {
    Name: "兽面人",
    HP: 300,
    ATK: 100,
    DEF: 100,
    Gold: 13,
    XP: 8,
    MP: 0,
  },
  [RoleTiles.BAT]: {
    Name: "小蝙蝠",
    HP: 100,
    ATK: 20,
    DEF: 5,
    Gold: 3,
    XP: 3,
    MP: 0,
  },
  [RoleTiles.MAGICIAN]: {
    Name: "初级魔术师",
    HP: 125,
    ATK: 50,
    DEF: 25,
    Gold: 7,
    XP: 10,
    MP: 0,
  },
  [RoleTiles.SKELETON]: {
    Name: "骷髅人",
    HP: 100,
    ATK: 25,
    DEF: 5,
    Gold: 5,
    XP: 4,
    MP: 0,
  },
  [RoleTiles.SKELETON_SOLDIER]: {
    Name: "骷髅士兵",
    HP: 150,
    ATK: 40,
    DEF: 20,
    Gold: 8,
    XP: 6,
    MP: 0,
  },
  [RoleTiles.BAT_BIG]: {
    Name: "大蝙蝠",
    HP: 150,
    ATK: 65,
    DEF: 30,
    Gold: 10,
    XP: 8,
    MP: 0,
  },
  [RoleTiles.SKELETON_QUEUE]: {
    Name: "骷髅队长",
    HP: 400,
    ATK: 90,
    DEF: 50,
    Gold: 15,
    XP: 12,
    MP: 0,
  },
  [RoleTiles.STONE_MONSTER]: {
    Name: "石头怪人",
    HP: 500,
    ATK: 115,
    DEF: 65,
    Gold: 15,
    XP: 15,
    MP: 0,
  },
  [RoleTiles.MAGICIAN_LINEN]: {
    Name: "麻衣法师",
    HP: 250,
    ATK: 120,
    DEF: 70,
    Gold: 20,
    XP: 17,
    MP: 0,
  },
  [RoleTiles.BAT_RED]: {
    Name: "红蝙蝠",
    HP: 550,
    ATK: 160,
    DEF: 90,
    Gold: 25,
    XP: 20,
    MP: 0,
  },
  [RoleTiles.MAGICIAN_HEIGHT]: {
    Name: "高级法师",
    HP: 100,
    ATK: 200,
    DEF: 110,
    Gold: 30,
    XP: 25,
    MP: 0,
  },
  [RoleTiles.SLIME_KING]: {
    Name: "怪王",
    HP: 700,
    ATK: 250,
    DEF: 125,
    Gold: 32,
    XP: 30,
    MP: 0,
  },
  [RoleTiles.KNIGHT_WHITE]: {
    Name: "白衣武士",
    HP: 1300,
    ATK: 300,
    DEF: 150,
    Gold: 40,
    XP: 35,
    MP: 0,
  },
  [RoleTiles.WEISHI_JIN]: {
    Name: "金卫士",
    HP: 850,
    ATK: 350,
    DEF: 200,
    Gold: 45,
    XP: 40,
    MP: 0,
  },
  [RoleTiles.MAGICIAN_RED]: {
    Name: "红衣法师",
    HP: 500,
    ATK: 400,
    DEF: 260,
    Gold: 47,
    XP: 45,
    MP: 0,
  },
  [RoleTiles.ORC_WARRIOR]: {
    Name: "兽面武士",
    HP: 900,
    ATK: 450,
    DEF: 330,
    Gold: 50,
    XP: 50,
    MP: 0,
  },
  [RoleTiles.GUARD_PRIMARY]: {
    Name: "初级卫兵",
    HP: 450,
    ATK: 150,
    DEF: 90,
    Gold: 22,
    XP: 19,
    MP: 0,
  },
  [RoleTiles.GUARD_UNDERWORLD]: {
    Name: "冥卫兵",
    HP: 1250,
    ATK: 500,
    DEF: 400,
    Gold: 55,
    XP: 55,
    MP: 0,
  },
  [RoleTiles.GUARD_HEIGHT]: {
    Name: "高级卫兵",
    HP: 1500,
    ATK: 560,
    DEF: 460,
    Gold: 60,
    XP: 60,
    MP: 0,
  },
  [RoleTiles.SWORDSMAN_BOTH_HANDS]: {
    Name: "双手剑士",
    HP: 1200,
    ATK: 620,
    DEF: 520,
    Gold: 65,
    XP: 75,
    MP: 0,
  },
  [RoleTiles.WARRIOR_UNDERWORLD]: {
    Name: "冥战士",
    HP: 2000,
    ATK: 680,
    DEF: 590,
    Gold: 70,
    XP: 65,
    MP: 0,
  },
  [RoleTiles.METALS_QUEUE]: {
    Name: "金队长",
    HP: 900,
    ATK: 750,
    DEF: 650,
    Gold: 77,
    XP: 70,
    MP: 0,
  },
  [RoleTiles.MAGICIAN_QUICK]: {
    Name: "灵法师",
    HP: 1500,
    ATK: 830,
    DEF: 730,
    Gold: 80,
    XP: 70,
    MP: 0,
  },
  [RoleTiles.UNDERWORLD_QUEUE]: {
    Name: "冥队长",
    HP: 2500,
    ATK: 900,
    DEF: 850,
    Gold: 84,
    XP: 75,
    MP: 0,
  },
  [RoleTiles.KNIGHT_QUEUE]: {
    Name: "灵武士",
    HP: 1200,
    ATK: 980,
    DEF: 900,
    Gold: 88,
    XP: 75,
    MP: 0,
  },
  [RoleTiles.DEVIL_RED]: {
    Name: "红衣魔王",
    HP: 15000,
    ATK: 1000,
    DEF: 1000,
    Gold: 100,
    XP: 100,
    MP: 0,
  },
  [RoleTiles.WARRIOR_SHADOW]: {
    Name: "影子战士",
    HP: 3100,
    ATK: 1150,
    DEF: 1050,
    Gold: 92,
    XP: 80,
    MP: 0,
  },
  [RoleTiles.DEVIL_QUEUE]: {
    Name: "冥灵魔王",
    HP: 45000,
    ATK: 2550,
    DEF: 2250,
    Gold: 312,
    XP: 275,
    MP: 0,
  },
  [RoleTiles.DRAGON]: {
    Name: "巨龙",
    HP: 45000,
    ATK: 2550,
    DEF: 2250,
    Gold: 312,
    XP: 275,
    MP: 0,
  },
  [RoleTiles.OCTOPUS]: {
    Name: "八爪鱼",
    HP: 45000,
    ATK: 2550,
    DEF: 2250,
    Gold: 312,
    XP: 275,
    MP: 0,
  },
};
